<a href="https://colab.research.google.com/github/Luyao-Xu/3-Class-Speech-Command-Classification/blob/main/03_DL_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import os

base_path = '/content/drive/MyDrive/speech_commands_project'
log_path = '/content/drive/MyDrive/speech_commands_project/logs'
results_path = '/content/drive/MyDrive/speech_commands_project/results'

os.makedirs(log_path, exist_ok=True)
os.makedirs(results_path, exist_ok=True)

print(f"Directories ready.\nLogs: {log_path}\nResults: {results_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Directories ready.
Logs: /content/drive/MyDrive/speech_commands_project/logs
Results: /content/drive/MyDrive/speech_commands_project/results

### Data Preparation (The 2D Loader)

In [ ]:
!pip install "numpy<2.0"
!pip install -q tf_keras
!pip install -q tensorflow-model-optimization
import os
os.environ['TF_USE_LEGACY_KERAS'] = '1'

import pandas as pd
import time
import numpy as np
import tensorflow as tf
import tf_keras
from tf_keras import layers, models
from tf_keras.optimizers import Adam
import tensorflow_model_optimization as tfmot

Requirement already satisfied: numpy<2.0 in /usr/local/lib/python3.12/dist-packages (1.26.4)

In [ ]:
# Description: Comparison of Standard CNN, SqueezeNet, and UltraLight with QAT/PTQ
# Author: [Xu Luyao]

config = {
    "version": "1.2.0",
    "input_shape": (40, 32, 1),
    "num_classes": 3,
    "batch_size": 32,
    "initial_epochs": 30,
    "qat_fine_tune_epochs": 8,
    "learning_rate_base": 0.001,
    "learning_rate_qat": 1e-5,
    "random_seed": 42
}

import numpy as np
import tensorflow as tf
tf.random.set_seed(config["random_seed"])
np.random.seed(config["random_seed"])

In [ ]:
# Path to your processed data
processed_path = '/content/drive/MyDrive/speech_commands_project/data/processed'

# Load files
X_train = np.load(os.path.join(processed_path, 'X_train.npy'))
y_train = np.load(os.path.join(processed_path, 'y_train.npy'))
X_val = np.load(os.path.join(processed_path, 'X_val.npy'))
y_val = np.load(os.path.join(processed_path, 'y_val.npy'))
X_test = np.load(os.path.join(processed_path, 'X_test.npy'))
y_test = np.load(os.path.join(processed_path, 'y_test.npy'))

# Reshape for CNN: (Samples, Height, Width, Channels)
# Your MFCCs are 40x32
X_train = X_train.reshape(X_train.shape[0], 40, 32, 1)
X_val = X_val.reshape(X_val.shape[0], 40, 32, 1)
X_test = X_test.reshape(X_test.shape[0], 40, 32, 1)

print(f"Data ready for CNN. Train shape: {X_train.shape}")

Data ready for CNN. Train shape: (7492, 40, 32, 1)

#### Model A:Simple 2D CNN (Baseline)
##### Uses classic 2D convolutions. This is the high-parameter reference point to show why optimization is necessary.

In [ ]:
def build_simple_cnn_for_qat(input_shape, num_classes):
    return tf_keras.Sequential([
        tf_keras.layers.Input(shape=input_shape),
        tf_keras.layers.Conv2D(32, (3,3), activation='relu'),
        tf_keras.layers.MaxPooling2D((2,2)),
        tf_keras.layers.Conv2D(64, (3,3), activation='relu'),
        tf_keras.layers.MaxPooling2D((2,2)),
        tf_keras.layers.Flatten(),
        tf_keras.layers.Dense(64, activation='relu'),
        tf_keras.layers.Dropout(0.3),
        tf_keras.layers.Dense(3, activation='softmax')
    ])

model_a = build_simple_cnn_for_qat((40, 32, 1), 3)
model_a.compile(
    optimizer=tf_keras.optimizers.Adam(learning_rate=0.0001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_a.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_9 (Conv2D)           (None, 38, 30, 32)        320

 max_pooling2d_5 (MaxPoolin  (None, 19, 15, 32)        0
 g2D)

 conv2d_10 (Conv2D)          (None, 17, 13, 64)        18496

 max_pooling2d_6 (MaxPoolin  (None, 8, 6, 64)          0
 g2D)

 flatten_1 (Flatten)         (None, 3072)              0

 dense_5 (Dense)             (None, 64)                196672

 dropout_2 (Dropout)         (None, 64)                0

 dense_6 (Dense)             (None, 3)                 195

=================================================================
Total params: 215683 (842.51 KB)
Trainable params: 215683 (842.51 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

### Model B:Mini-SqueezeNet
##### A specific lightweight architecture, uses Fire Modules (Squeeze & Expand).
 how 1*1 convolutions can 'squeeze' information to save memory.

In [ ]:
def fire_module(x, squeeze, expand):
    s = layers.Conv2D(squeeze, (1, 1), padding='same', activation='relu')(x)
    e1 = layers.Conv2D(expand, (1, 1), padding='same', activation='relu')(s)
    e3 = layers.Conv2D(expand, (3, 3), padding='same', activation='relu')(s)
    return layers.Concatenate()([e1, e3])

def build_squeezenet(input_shape, num_classes):
    inputs = layers.Input(shape=input_shape)
    x = layers.Conv2D(16, (3, 3), strides=(1, 1), padding='same', activation='relu')(inputs)
    x = layers.MaxPooling2D(pool_size=(2, 2))(x)

    # The Fire Modules
    x = fire_module(x, squeeze=8, expand=16)
    x = fire_module(x, squeeze=8, expand=16)

    x = layers.GlobalAveragePooling2D()(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs, name="Model_B_SqueezeNet")
    return model

# Create and inspect
model_b = build_squeezenet((40, 32, 1), 3)
model_b.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model_b.summary()

Model: "Model_B_SqueezeNet"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_5 (InputLayer)        [(None, 40, 32, 1)]          0         []

 conv2d_11 (Conv2D)          (None, 40, 32, 16)           160       ['input_5[0][0]']

 max_pooling2d_7 (MaxPoolin  (None, 20, 16, 16)           0         ['conv2d_11[0][0]']
 g2D)

 conv2d_12 (Conv2D)          (None, 20, 16, 8)            136       ['max_pooling2d_7[0][0]']

 conv2d_13 (Conv2D)          (None, 20, 16, 16)           144       ['conv2d_12[0][0]']

 conv2d_14 (Conv2D)          (None, 20, 16, 16)           1168      ['conv2d_12[0][0]']

 concatenate_2 (Concatenate  (None, 20, 16, 32)           0         ['conv2d_13[0][0]',
 )                                                                   'conv2d_14[0][0]']

 conv2d_15 (Conv2D)          (None, 20, 16, 8)            264       ['concatenate_2[0][0]']

 conv2d_16 (Conv2D)          (None, 20, 16, 16)           144       ['conv2d_15[0][0]']

 conv2d_17 (Conv2D)          (None, 20, 16, 16)           1168      ['conv2d_15[0][0]']

 concatenate_3 (Concatenate  (None, 20, 16, 32)           0         ['conv2d_16[0][0]',
 )                                                                   'conv2d_17[0][0]']

 global_average_pooling2d_2  (None, 32)                   0         ['concatenate_3[0][0]']
  (GlobalAveragePooling2D)

 dense_7 (Dense)             (None, 3)                    99        ['global_average_pooling2d_2[0
                                                                    ][0]']

==================================================================================================
Total params: 3283 (12.82 KB)
Trainable params: 3283 (12.82 KB)
Non-trainable params: 0 (0.00 Byte)
__________________________________________________________________________________________________

### Model C:Ultra-Lightweight (MobileNet-style)
##### MobileNet-inspired, uses Depthwise Separable Convolutions and Global Average Pooling.

In [ ]:
def build_ultralight_cnn(input_shape, num_classes):
    model = models.Sequential([
        layers.Input(shape=input_shape),

        # Block 1: Feature Extraction
        layers.SeparableConv2D(16, (3, 3), padding='same', activation='relu'),
        layers.MaxPooling2D((2, 2)),

        # Block 2: Feature Extraction
        layers.SeparableConv2D(32, (3, 3), padding='same', activation='relu'),
        layers.MaxPooling2D((2, 2)),

        # The "Embedded Trick": Global Average Pooling instead of Flatten
        layers.GlobalAveragePooling2D(),

        # Final Classification Head
        layers.Dense(32, activation='relu'),
        layers.Dropout(0.2),
        layers.Dense(num_classes, activation='softmax')
    ])
    return model

# 1. Initialize Model C
model_c = build_ultralight_cnn((40, 32, 1), 3)

# 2. Compile it (This ensures the 'Adam' name is recognized)
model_c.compile(optimizer=Adam(learning_rate=0.001),
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])

# 3. View Summary
model_c.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 separable_conv2d_4 (Separa  (None, 40, 32, 16)        41
 bleConv2D)

 max_pooling2d_10 (MaxPooli  (None, 20, 16, 16)        0
 ng2D)

 separable_conv2d_5 (Separa  (None, 20, 16, 32)        688
 bleConv2D)

 max_pooling2d_11 (MaxPooli  (None, 10, 8, 32)         0
 ng2D)

 global_average_pooling2d_4  (None, 32)                0
  (GlobalAveragePooling2D)

 dense_10 (Dense)            (None, 32)                1056

 dropout_4 (Dropout)         (None, 32)                0

 dense_11 (Dense)            (None, 3)                 99

=================================================================
Total params: 1884 (7.36 KB)
Trainable params: 1884 (7.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

##**Traing**
##### I utilized a batch size of 32 and 30 epochs to ensure stable gradient convergence while avoiding overfitting on the phonetically similar classes. I maintained the standard Adam learning rate of 0.001 for the initial training phase.

In [ ]:
models_to_train = {
    "Model_A_Standard": model_a,
    "Model_B_Separable": model_b,
    "Model_C_UltraLight": model_c
}

EPOCHS = 30
BATCH_SIZE = 32
LEARNING_RATE = 0.001

histories = {}
training_times = {}

for name, model in models_to_train.items():
    print(f"\n Starting Training for {name} ")

    model.compile(
        optimizer=Adam(learning_rate=LEARNING_RATE),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    start_train = time.time()

    history = model.fit(
        X_train, y_train,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        validation_data=(X_val, y_val),
        verbose=1
    )
    end_train = time.time()

    training_times[name] = end_train - start_train
    histories[name] = history

    history_df = pd.DataFrame(history.history)
    history_csv = os.path.join(log_path, f"{name}_training_log.csv")
    history_df.to_csv(history_csv, index=False)

    print(f" {name} log successfully saved to: {history_csv}")
    print(f"{name} Training Complete.")

 Starting Training for Model_A_Standard
Epoch 1/30
235/235 [==============================] - 24s 89ms/step - loss: 0.7550 - accuracy: 0.7090 - val_loss: 0.4182 - val_accuracy: 0.8239
Epoch 2/30
235/235 [==============================] - 14s 58ms/step - loss: 0.3452 - accuracy: 0.8619 - val_loss: 0.2845 - val_accuracy: 0.8773
Epoch 3/30
235/235 [==============================] - 13s 56ms/step - loss: 0.2697 - accuracy: 0.8984 - val_loss: 0.3291 - val_accuracy: 0.8837
Epoch 4/30
235/235 [==============================] - 12s 49ms/step - loss: 0.2223 - accuracy: 0.9132 - val_loss: 0.2618 - val_accuracy: 0.8943
Epoch 5/30
235/235 [==============================] - 13s 54ms/step - loss: 0.1908 - accuracy: 0.9255 - val_loss: 0.2448 - val_accuracy: 0.9072
Epoch 6/30
235/235 [==============================] - 13s 56ms/step - loss: 0.1658 - accuracy: 0.9365 - val_loss: 0.2512 - val_accuracy: 0.9104
Epoch 7/30
235/235 [==============================] - 14s 60ms/step - loss: 0.1558 - accuracy: 0.9414 - val_loss: 0.2654 - val_accuracy: 0.9072
Epoch 8/30
235/235 [==============================] - 14s 58ms/step - loss: 0.1269 - accuracy: 0.9510 - val_loss: 0.2713 - val_accuracy: 0.9093
Epoch 9/30
235/235 [==============================] - 13s 57ms/step - loss: 0.0986 - accuracy: 0.9638 - val_loss: 0.2774 - val_accuracy: 0.9136
Epoch 10/30
235/235 [==============================] - 12s 51ms/step - loss: 0.1061 - accuracy: 0.9584 - val_loss: 0.2988 - val_accuracy: 0.8986
Epoch 11/30
235/235 [==============================] - 15s 63ms/step - loss: 0.0973 - accuracy: 0.9633 - val_loss: 0.3162 - val_accuracy: 0.9093
Epoch 12/30
235/235 [==============================] - 12s 53ms/step - loss: 0.0805 - accuracy: 0.9689 - val_loss: 0.3236 - val_accuracy: 0.9200
Epoch 13/30
235/235 [==============================] - 13s 57ms/step - loss: 0.0597 - accuracy: 0.9790 - val_loss: 0.4247 - val_accuracy: 0.8933
Epoch 14/30
235/235 [==============================] - 13s 57ms/step - loss: 0.0618 - accuracy: 0.9758 - val_loss: 0.4007 - val_accuracy: 0.9018
Epoch 15/30
235/235 [==============================] - 13s 57ms/step - loss: 0.0674 - accuracy: 0.9749 - val_loss: 0.3871 - val_accuracy: 0.9125
Epoch 16/30
235/235 [==============================] - 13s 54ms/step - loss: 0.0654 - accuracy: 0.9773 - val_loss: 0.4807 - val_accuracy: 0.8858
Epoch 17/30
235/235 [==============================] - 12s 49ms/step - loss: 0.0536 - accuracy: 0.9793 - val_loss: 0.3811 - val_accuracy: 0.9136
Epoch 18/30
235/235 [==============================] - 13s 56ms/step - loss: 0.0443 - accuracy: 0.9834 - val_loss: 0.4251 - val_accuracy: 0.9072
Epoch 19/30
235/235 [==============================] - 14s 58ms/step - loss: 0.0392 - accuracy: 0.9855 - val_loss: 0.5040 - val_accuracy: 0.9061
Epoch 20/30
235/235 [==============================] - 13s 57ms/step - loss: 0.0970 - accuracy: 0.9661 - val_loss: 0.4587 - val_accuracy: 0.9093
Epoch 21/30
235/235 [==============================] - 13s 57ms/step - loss: 0.0384 - accuracy: 0.9867 - val_loss: 0.4825 - val_accuracy: 0.9082
Epoch 22/30
235/235 [==============================] - 12s 52ms/step - loss: 0.0266 - accuracy: 0.9904 - val_loss: 0.4866 - val_accuracy: 0.9061
Epoch 23/30
235/235 [==============================] - 12s 52ms/step - loss: 0.0310 - accuracy: 0.9893 - val_loss: 0.4680 - val_accuracy: 0.9114
Epoch 24/30
235/235 [==============================] - 13s 56ms/step - loss: 0.0593 - accuracy: 0.9824 - val_loss: 0.5317 - val_accuracy: 0.9082
Epoch 25/30
235/235 [==============================] - 14s 58ms/step - loss: 0.0387 - accuracy: 0.9861 - val_loss: 0.3956 - val_accuracy: 0.9104
Epoch 26/30
235/235 [==============================] - 13s 56ms/step - loss: 0.0390 - accuracy: 0.9856 - val_loss: 0.5236 - val_accuracy: 0.9093
Epoch 27/30
235/235 [==============================] - 14s 60ms/step - loss: 0.0574 - accuracy: 0.9813 - val_loss: 0.5567 - val_accuracy: 0.9072
Epoch 28/30
235/235 [==============================] - 12s 50ms/step - loss: 0.0249 - accuracy: 0.9917 - val_loss: 0.5266 - val_accuracy: 0.9114
Epoch 29/30
235/235 [==============================] - 12s 53ms/step - loss: 0.0206 - accuracy: 0.9936 - val_loss: 0.5807 - val_accuracy: 0.9039
Epoch 30/30
235/235 [==============================] - 13s 57ms/step - loss: 0.0323 - accuracy: 0.9884 - val_loss: 0.5643 - val_accuracy: 0.9061
 Model_A_Standard log successfully saved to: /content/drive/MyDrive/speech_commands_project/logs/Model_A_Standard_training_log.csv
Model_A_Standard Training Complete.

 Starting Training for Model_B_Separable
Epoch 1/30
235/235 [==============================] - 12s 42ms/step - loss: 0.8725 - accuracy: 0.6078 - val_loss: 0.6734 - val_accuracy: 0.7204
Epoch 2/30
235/235 [==============================] - 11s 48ms/step - loss: 0.4881 - accuracy: 0.7986 - val_loss: 0.4592 - val_accuracy: 0.8079
Epoch 3/30
235/235 [==============================] - 10s 43ms/step - loss: 0.4218 - accuracy: 0.8285 - val_loss: 0.5341 - val_accuracy: 0.7705
Epoch 4/30
235/235 [==============================] - 10s 41ms/step - loss: 0.3950 - accuracy: 0.8394 - val_loss: 0.4099 - val_accuracy: 0.8228
Epoch 5/30
235/235 [==============================] - 12s 49ms/step - loss: 0.3762 - accuracy: 0.8444 - val_loss: 0.4277 - val_accuracy: 0.8100
Epoch 6/30
235/235 [==============================] - 10s 42ms/step - loss: 0.3559 - accuracy: 0.8590 - val_loss: 0.3397 - val_accuracy: 0.8591
Epoch 7/30
235/235 [==============================] - 10s 43ms/step - loss: 0.3484 - accuracy: 0.8648 - val_loss: 0.3450 - val_accuracy: 0.8623
Epoch 8/30
235/235 [==============================] - 11s 48ms/step - loss: 0.3189 - accuracy: 0.8803 - val_loss: 0.3633 - val_accuracy: 0.8677
Epoch 9/30
235/235 [==============================] - 10s 42ms/step - loss: 0.3012 - accuracy: 0.8860 - val_loss: 0.3926 - val_accuracy: 0.8143
Epoch 10/30
235/235 [==============================] - 10s 42ms/step - loss: 0.2849 - accuracy: 0.8936 - val_loss: 0.2871 - val_accuracy: 0.8975
Epoch 11/30
235/235 [==============================] - 11s 49ms/step - loss: 0.2728 - accuracy: 0.8998 - val_loss: 0.2759 - val_accuracy: 0.9007
Epoch 12/30
235/235 [==============================] - 10s 41ms/step - loss: 0.2570 - accuracy: 0.9052 - val_loss: 0.2765 - val_accuracy: 0.8943
Epoch 13/30
235/235 [==============================] - 10s 43ms/step - loss: 0.2447 - accuracy: 0.9126 - val_loss: 0.2962 - val_accuracy: 0.8965
Epoch 14/30
235/235 [==============================] - 11s 48ms/step - loss: 0.2453 - accuracy: 0.9092 - val_loss: 0.2387 - val_accuracy: 0.9082
Epoch 15/30
235/235 [==============================] - 10s 41ms/step - loss: 0.2294 - accuracy: 0.9174 - val_loss: 0.2583 - val_accuracy: 0.9072
Epoch 16/30
235/235 [==============================] - 10s 45ms/step - loss: 0.2313 - accuracy: 0.9148 - val_loss: 0.2124 - val_accuracy: 0.9285
Epoch 17/30
235/235 [==============================] - 11s 49ms/step - loss: 0.2122 - accuracy: 0.9214 - val_loss: 0.2721 - val_accuracy: 0.8922
Epoch 18/30
235/235 [==============================] - 10s 44ms/step - loss: 0.2232 - accuracy: 0.9174 - val_loss: 0.2289 - val_accuracy: 0.9082
Epoch 19/30
235/235 [==============================] - 10s 43ms/step - loss: 0.2066 - accuracy: 0.9254 - val_loss: 0.3050 - val_accuracy: 0.8986
Epoch 20/30
235/235 [==============================] - 12s 49ms/step - loss: 0.1988 - accuracy: 0.9250 - val_loss: 0.2258 - val_accuracy: 0.9157
Epoch 21/30
235/235 [==============================] - 11s 48ms/step - loss: 0.2104 - accuracy: 0.9250 - val_loss: 0.2123 - val_accuracy: 0.9189
Epoch 22/30
235/235 [==============================] - 9s 40ms/step - loss: 0.1960 - accuracy: 0.9282 - val_loss: 0.2505 - val_accuracy: 0.8986
Epoch 23/30
235/235 [==============================] - 16s 70ms/step - loss: 0.1940 - accuracy: 0.9273 - val_loss: 0.2152 - val_accuracy: 0.9221
Epoch 24/30
235/235 [==============================] - 30s 129ms/step - loss: 0.1980 - accuracy: 0.9289 - val_loss: 0.2055 - val_accuracy: 0.9274
Epoch 25/30
235/235 [==============================] - 17s 71ms/step - loss: 0.1915 - accuracy: 0.9302 - val_loss: 0.2276 - val_accuracy: 0.9050
Epoch 26/30
235/235 [==============================] - 12s 49ms/step - loss: 0.1929 - accuracy: 0.9287 - val_loss: 0.2096 - val_accuracy: 0.9328
Epoch 27/30
235/235 [==============================] - 9s 39ms/step - loss: 0.1834 - accuracy: 0.9317 - val_loss: 0.2241 - val_accuracy: 0.9242
Epoch 28/30
235/235 [==============================] - 11s 48ms/step - loss: 0.1893 - accuracy: 0.9307 - val_loss: 0.2853 - val_accuracy: 0.9050
Epoch 29/30
235/235 [==============================] - 12s 51ms/step - loss: 0.1910 - accuracy: 0.9277 - val_loss: 0.1969 - val_accuracy: 0.9328
Epoch 30/30
235/235 [==============================] - 10s 43ms/step - loss: 0.1722 - accuracy: 0.9381 - val_loss: 0.2555 - val_accuracy: 0.8975
 Model_B_Separable log successfully saved to: /content/drive/MyDrive/speech_commands_project/logs/Model_B_Separable_training_log.csv
Model_B_Separable Training Complete.

 Starting Training for Model_C_UltraLight
Epoch 1/30
235/235 [==============================] - 10s 35ms/step - loss: 1.0913 - accuracy: 0.4115 - val_loss: 1.0123 - val_accuracy: 0.4717
Epoch 2/30
235/235 [==============================] - 10s 44ms/step - loss: 0.9969 - accuracy: 0.4798 - val_loss: 0.9295 - val_accuracy: 0.5486
Epoch 3/30
235/235 [==============================] - 7s 32ms/step - loss: 0.8917 - accuracy: 0.5901 - val_loss: 0.8229 - val_accuracy: 0.6147
Epoch 4/30
235/235 [==============================] - 11s 48ms/step - loss: 0.7433 - accuracy: 0.6847 - val_loss: 0.6719 - val_accuracy: 0.6937
Epoch 5/30
235/235 [==============================] - 9s 40ms/step - loss: 0.6065 - accuracy: 0.7487 - val_loss: 0.5237 - val_accuracy: 0.7513
Epoch 6/30
235/235 [==============================] - 9s 40ms/step - loss: 0.5453 - accuracy: 0.7735 - val_loss: 0.5106 - val_accuracy: 0.7705
Epoch 7/30
235/235 [==============================] - 11s 47ms/step - loss: 0.5148 - accuracy: 0.7868 - val_loss: 0.5140 - val_accuracy: 0.7663
Epoch 8/30
235/235 [==============================] - 8s 32ms/step - loss: 0.4979 - accuracy: 0.7955 - val_loss: 0.4530 - val_accuracy: 0.8068
Epoch 9/30
235/235 [==============================] - 10s 43ms/step - loss: 0.4820 - accuracy: 0.8017 - val_loss: 0.4324 - val_accuracy: 0.8164
Epoch 10/30
235/235 [==============================] - 10s 41ms/step - loss: 0.4791 - accuracy: 0.7994 - val_loss: 0.4314 - val_accuracy: 0.8132
Epoch 11/30
235/235 [==============================] - 8s 34ms/step - loss: 0.4619 - accuracy: 0.8110 - val_loss: 0.4341 - val_accuracy: 0.8111
Epoch 12/30
235/235 [==============================] - 10s 44ms/step - loss: 0.4643 - accuracy: 0.8089 - val_loss: 0.4389 - val_accuracy: 0.8132
Epoch 13/30
235/235 [==============================] - 7s 31ms/step - loss: 0.4600 - accuracy: 0.8167 - val_loss: 0.4181 - val_accuracy: 0.8228
Epoch 14/30
235/235 [==============================] - 10s 44ms/step - loss: 0.4559 - accuracy: 0.8114 - val_loss: 0.4412 - val_accuracy: 0.8186
Epoch 15/30
235/235 [==============================] - 8s 35ms/step - loss: 0.4386 - accuracy: 0.8165 - val_loss: 0.3959 - val_accuracy: 0.8335
Epoch 16/30
235/235 [==============================] - 10s 41ms/step - loss: 0.4388 - accuracy: 0.8214 - val_loss: 0.4061 - val_accuracy: 0.8186
Epoch 17/30
235/235 [==============================] - 10s 43ms/step - loss: 0.4332 - accuracy: 0.8205 - val_loss: 0.4227 - val_accuracy: 0.8154
Epoch 18/30
235/235 [==============================] - 8s 34ms/step - loss: 0.4301 - accuracy: 0.8237 - val_loss: 0.3889 - val_accuracy: 0.8420
Epoch 19/30
235/235 [==============================] - 10s 44ms/step - loss: 0.4284 - accuracy: 0.8246 - val_loss: 0.3746 - val_accuracy: 0.8485
Epoch 20/30
235/235 [==============================] - 7s 31ms/step - loss: 0.4254 - accuracy: 0.8245 - val_loss: 0.4094 - val_accuracy: 0.8356
Epoch 21/30
235/235 [==============================] - 10s 44ms/step - loss: 0.4246 - accuracy: 0.8215 - val_loss: 0.4236 - val_accuracy: 0.8132
Epoch 22/30
235/235 [==============================] - 9s 38ms/step - loss: 0.4161 - accuracy: 0.8263 - val_loss: 0.3987 - val_accuracy: 0.8271
Epoch 23/30
235/235 [==============================] - 9s 37ms/step - loss: 0.4162 - accuracy: 0.8258 - val_loss: 0.4023 - val_accuracy: 0.8335
Epoch 24/30
235/235 [==============================] - 10s 44ms/step - loss: 0.4053 - accuracy: 0.8345 - val_loss: 0.3728 - val_accuracy: 0.8346
Epoch 25/30
235/235 [==============================] - 7s 32ms/step - loss: 0.4045 - accuracy: 0.8336 - val_loss: 0.3642 - val_accuracy: 0.8559
Epoch 26/30
235/235 [==============================] - 10s 44ms/step - loss: 0.3984 - accuracy: 0.8374 - val_loss: 0.3864 - val_accuracy: 0.8314
Epoch 27/30
235/235 [==============================] - 7s 32ms/step - loss: 0.4069 - accuracy: 0.8309 - val_loss: 0.3627 - val_accuracy: 0.8549
Epoch 28/30
235/235 [==============================] - 10s 44ms/step - loss: 0.3961 - accuracy: 0.8346 - val_loss: 0.3574 - val_accuracy: 0.8591
Epoch 29/30
235/235 [==============================] - 9s 40ms/step - loss: 0.3993 - accuracy: 0.8373 - val_loss: 0.4033 - val_accuracy: 0.8239
Epoch 30/30
235/235 [==============================] - 9s 37ms/step - loss: 0.4016 - accuracy: 0.8350 - val_loss: 0.3563 - val_accuracy: 0.8602
 Model_C_UltraLight log successfully saved to: /content/drive/MyDrive/speech_commands_project/logs/Model_C_UltraLight_training_log.csv
Model_C_UltraLight Training Complete.

### The Quantitative Comparison

In [ ]:
def generate_comparison_table(models_dict, history_dict, training_times_dict):
    stats = []

    for name, model in models_dict.items():

        params = model.count_params()
        # Memory estimation: each param is 4 bytes (float32)
        size_kb = (params * 4) / 1024

        final_val_acc = history_dict[name].history['val_accuracy'][-1]

        _ = model.predict(X_test[:5], verbose=0)

        test_samples = X_test[:100]
        start_inf = time.perf_counter()
        _ = model.predict(test_samples, verbose=0)
        end_inf = time.perf_counter()

        # Calculate ms per sample
        inf_latency_ms = ((end_inf - start_inf) / 100) * 1000

        stats.append({
            "Model Architecture": name,
            "Total Parameters": f"{params:,}",
            "Est. Memory (KB)": round(size_kb, 2),
            "Final Val Acc": f"{final_val_acc:.2%}",
            "Train Time (sec)": round(training_times_dict[name], 2),
            "Inf Latency (ms)": round(inf_latency_ms, 3)
        })
    return pd.DataFrame(stats)

# Generate and print
results_df = generate_comparison_table(models_to_train, histories, training_times)
print("\n Final Project Analysis: DL Models")
print(results_df)

baseline_csv = os.path.join(results_path, 'baseline_model_comparison.csv')
results_df.to_csv(baseline_csv, index=False)

 Final Project Analysis: DL Models
   Model Architecture Total Parameters  Est. Memory (KB) Final Val Acc  \
0    Model_A_Standard          215,683            842.51        90.61%
1   Model_B_Separable            3,283             12.82        89.75%
2  Model_C_UltraLight            1,884              7.36        86.02%

   Train Time (sec)  Inf Latency (ms)
0            446.26             1.301
1            350.05             1.069
2            277.58             1.052

## **Post-Training Quantization (PTQ)**
##### In this step, we capture the architectural parameters and the conversion time (the "train time" of the optimization process).

In [ ]:
ptq_metadata = []

def representative_data_gen():
    for i in range(100):
        data = np.expand_dims(X_train[i], axis=0).astype(np.float32)
        yield [data]

for name, model in models_to_train.items():
    print(f"\n Processing PTQ: {name}")
    total_params = model.count_params()

    try:
        start_ptq = time.time()

        saved_model_path = os.path.join(results_path, f'{name}_ptq_saved')
        model.export(saved_model_path)

        converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path)
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = representative_data_gen
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.float32
        converter.inference_output_type = tf.float32

        tflite_model = converter.convert()
        ptq_duration = time.time() - start_ptq

        file_path = os.path.join(results_path, f'{name}_ptq.tflite')
        with open(file_path, 'wb') as f:
            f.write(tflite_model)

        ptq_metadata.append({
            "Model": name,
            "Type": "PTQ",
            "Total Parameters": f"{total_params:,}",
            "Train Time (sec)": round(ptq_duration, 2),
            "Size (KB)": round(len(tflite_model) / 1024, 2),
            "path": file_path
        })
        print(f" {name} PTQ saved. Time: {ptq_duration:.2f}s")

    except Exception as e:
        print(f" Error converting {name}: {str(e)}")

pd.DataFrame(ptq_metadata).to_csv(os.path.join(log_path, 'ptq_process_summary.csv'), index=False)

 Processing PTQ: Model_A_Standard
Saved artifact at '/content/drive/MyDrive/speech_commands_project/results/Model_A_Standard_ptq_saved'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 40, 32, 1), dtype=tf.float32, name='input_4')
Output Type:
  TensorSpec(shape=(None, 3), dtype=tf.float32, name=None)
Captures:
  135897467628880: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897976652240: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333059024: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333056528: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333057296: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333056336: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333058832: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333057488: TensorSpec(shape=(), dtype=tf.resource, name=None)
 Model_A_Standard PTQ saved. Time: 2.74s

 Processing PTQ: Model_B_Separable
Saved artifact at '/content/drive/MyDrive/speech_commands_project/results/Model_B_Separable_ptq_saved'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 40, 32, 1), dtype=tf.float32, name='input_5')
Output Type:
  TensorSpec(shape=(None, 3), dtype=tf.float32, name=None)
Captures:
  135897467617744: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333055952: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333057680: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333058256: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333055760: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333070544: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333058448: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333069008: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135900305618512: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333070352: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333058640: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333069584: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333069968: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333069776: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333070160: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333067472: TensorSpec(shape=(), dtype=tf.resource, name=None)
 Model_B_Separable PTQ saved. Time: 1.96s

 Processing PTQ: Model_C_UltraLight
Saved artifact at '/content/drive/MyDrive/speech_commands_project/results/Model_C_UltraLight_ptq_saved'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 40, 32, 1), dtype=tf.float32, name='input_7')
Output Type:
  TensorSpec(shape=(None, 3), dtype=tf.float32, name=None)
Captures:
  135896925144848: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925144464: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925145616: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925144656: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925145040: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925146192: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925145232: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925146576: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925143312: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925146960: TensorSpec(shape=(), dtype=tf.resource, name=None)
 Model_C_UltraLight PTQ saved. Time: 1.68s

## **Quantization-Aware Training (QAT)**

In [ ]:
qat_metadata = []
qat_tflite_files = {}

qat_models = {
    "Model_A_Standard": tfmot.quantization.keras.quantize_model(model_a),
    "Model_B_Separable": tfmot.quantization.keras.quantize_model(model_b),
    "Model_C_UltraLight": tfmot.quantization.keras.quantize_model(model_c)
}

for name, q_model in qat_models.items():
    print(f"\n Starting QAT Fine-tuning: {name}")
    total_params = q_model.count_params()

    q_model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    #  training timer
    start_train = time.time()
    history = q_model.fit(
        X_train, y_train,
        epochs=8,
        batch_size=32,
        validation_data=(X_val, y_val),
        verbose=1
    )
    train_duration = time.time() - start_train

    pd.DataFrame(history.history).to_csv(os.path.join(log_path, f"{name}_qat_history.csv"), index=False)

    # Convert to TFLite
    saved_qat_path = os.path.join(results_path, f'{name}_qat_saved')
    q_model.export(saved_qat_path)
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_qat_path)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_qat_model = converter.convert()

    file_path = os.path.join(results_path, f'{name}_qat.tflite')
    with open(file_path, 'wb') as f:
        f.write(tflite_qat_model)

    qat_metadata.append({
        "Model": name,
        "Type": "QAT",
        "Total Parameters": f"{total_params:,}",
        "Train Time (sec)": round(train_duration, 2),
        "Size (KB)": round(len(tflite_qat_model) / 1024, 2),
        "path": file_path
    })
    print(f" {name} QAT saved. Time: {train_duration:.2f}s")

pd.DataFrame(qat_metadata).to_csv(os.path.join(log_path, 'qat_process_summary.csv'), index=False)

 Starting QAT Fine-tuning: Model_A_Standard
Epoch 1/8
235/235 [==============================] - 35s 139ms/step - loss: 0.2850 - accuracy: 0.9014 - val_loss: 0.6363 - val_accuracy: 0.8495
Epoch 2/8
235/235 [==============================] - 22s 93ms/step - loss: 0.0409 - accuracy: 0.9863 - val_loss: 0.5343 - val_accuracy: 0.8922
Epoch 3/8
235/235 [==============================] - 15s 65ms/step - loss: 0.0191 - accuracy: 0.9923 - val_loss: 0.5388 - val_accuracy: 0.9061
Epoch 4/8
235/235 [==============================] - 15s 64ms/step - loss: 0.0180 - accuracy: 0.9933 - val_loss: 0.5459 - val_accuracy: 0.9050
Epoch 5/8
235/235 [==============================] - 15s 64ms/step - loss: 0.0134 - accuracy: 0.9941 - val_loss: 0.5591 - val_accuracy: 0.9072
Epoch 6/8
235/235 [==============================] - 16s 69ms/step - loss: 0.0149 - accuracy: 0.9947 - val_loss: 0.5605 - val_accuracy: 0.9082
Epoch 7/8
235/235 [==============================] - 22s 93ms/step - loss: 0.0111 - accuracy: 0.9964 - val_loss: 0.5742 - val_accuracy: 0.9136
Epoch 8/8
235/235 [==============================] - 15s 64ms/step - loss: 0.0154 - accuracy: 0.9941 - val_loss: 0.5723 - val_accuracy: 0.9114
Saved artifact at '/content/drive/MyDrive/speech_commands_project/results/Model_A_Standard_qat_saved'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 40, 32, 1), dtype=tf.float32, name='input_4')
Output Type:
  TensorSpec(shape=(None, 3), dtype=tf.float32, name=None)
Captures:
  135898665386256: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665393360: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665395664: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665397008: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665388560: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665400656: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925149456: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925149072: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665398352: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925146000: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925158672: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665393936: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925149264: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925148688: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665397392: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925145808: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925145424: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665399888: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925146384: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925143504: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665397776: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135896925148304: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135900303422480: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665402192: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135900153953936: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897469025936: TensorSpec(shape=(), dtype=tf.resource, name=None)
 Model_A_Standard QAT saved. Time: 156.40s

 Starting QAT Fine-tuning: Model_B_Separable
Epoch 1/8
235/235 [==============================] - 16s 59ms/step - loss: 1.1510 - accuracy: 0.4996 - val_loss: 0.8455 - val_accuracy: 0.6329
Epoch 2/8
235/235 [==============================] - 14s 58ms/step - loss: 0.7214 - accuracy: 0.7360 - val_loss: 0.7074 - val_accuracy: 0.7225
Epoch 3/8
235/235 [==============================] - 13s 57ms/step - loss: 0.5639 - accuracy: 0.8025 - val_loss: 0.5779 - val_accuracy: 0.7684
Epoch 4/8
235/235 [==============================] - 14s 59ms/step - loss: 0.4551 - accuracy: 0.8409 - val_loss: 0.4738 - val_accuracy: 0.8090
Epoch 5/8
235/235 [==============================] - 12s 51ms/step - loss: 0.3620 - accuracy: 0.8688 - val_loss: 0.3789 - val_accuracy: 0.8517
Epoch 6/8
235/235 [==============================] - 13s 55ms/step - loss: 0.2861 - accuracy: 0.8992 - val_loss: 0.3108 - val_accuracy: 0.8815
Epoch 7/8
235/235 [==============================] - 13s 56ms/step - loss: 0.2316 - accuracy: 0.9241 - val_loss: 0.2678 - val_accuracy: 0.9072
Epoch 8/8
235/235 [==============================] - 13s 56ms/step - loss: 0.1977 - accuracy: 0.9326 - val_loss: 0.2401 - val_accuracy: 0.9125
Saved artifact at '/content/drive/MyDrive/speech_commands_project/results/Model_B_Separable_qat_saved'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 40, 32, 1), dtype=tf.float32, name='input_5')
Output Type:
  TensorSpec(shape=(None, 3), dtype=tf.float32, name=None)
Captures:
  135897467629264: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467625040: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665386448: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467632720: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467625808: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333064976: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467624272: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467626576: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333071504: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467626000: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467627344: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333064784: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467626768: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467626192: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333061520: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467626384: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467627152: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333060560: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467628304: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467623504: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333064592: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467626960: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467632528: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333070928: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467628688: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467624080: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467621776: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467617360: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897333061328: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467619280: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467620048: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467621008: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661233936: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661235472: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467627536: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467618896: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661237200: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467631376: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661235088: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661233360: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467623120: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661237584: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661235856: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467630608: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661232016: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661232208: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661240464: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661240656: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661239696: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661238160: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467618704: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661238736: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661237968: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135897467630800: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661238544: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661238352: TensorSpec(shape=(), dtype=tf.resource, name=None)
 Model_B_Separable QAT saved. Time: 144.61s

 Starting QAT Fine-tuning: Model_C_UltraLight
Epoch 1/8
235/235 [==============================] - 21s 60ms/step - loss: 1.1266 - accuracy: 0.3795 - val_loss: 1.0535 - val_accuracy: 0.4280
Epoch 2/8
235/235 [==============================] - 24s 101ms/step - loss: 0.9950 - accuracy: 0.5019 - val_loss: 0.9156 - val_accuracy: 0.6019
Epoch 3/8
235/235 [==============================] - 17s 72ms/step - loss: 0.8452 - accuracy: 0.6371 - val_loss: 0.7630 - val_accuracy: 0.6809
Epoch 4/8
235/235 [==============================] - 11s 48ms/step - loss: 0.7156 - accuracy: 0.7165 - val_loss: 0.6035 - val_accuracy: 0.7609
Epoch 5/8
235/235 [==============================] - 9s 36ms/step - loss: 0.5916 - accuracy: 0.7679 - val_loss: 0.5005 - val_accuracy: 0.7951
Epoch 6/8
235/235 [==============================] - 11s 48ms/step - loss: 0.5072 - accuracy: 0.7950 - val_loss: 0.4352 - val_accuracy: 0.8207
Epoch 7/8
235/235 [==============================] - 11s 48ms/step - loss: 0.4413 - accuracy: 0.8163 - val_loss: 0.3974 - val_accuracy: 0.8346
Epoch 8/8
235/235 [==============================] - 8s 36ms/step - loss: 0.4132 - accuracy: 0.8261 - val_loss: 0.3833 - val_accuracy: 0.8388
Saved artifact at '/content/drive/MyDrive/speech_commands_project/results/Model_C_UltraLight_qat_saved'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 40, 32, 1), dtype=tf.float32, name='input_7')
Output Type:
  TensorSpec(shape=(None, 3), dtype=tf.float32, name=None)
Captures:
  135898661228944: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661228368: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665396240: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661230096: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661227792: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661228176: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661227024: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898665386640: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661226640: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661226448: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661234896: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661226256: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661226064: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661231248: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661225680: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661225488: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661225104: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661224720: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661229712: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661224912: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661227408: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661231632: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662414928: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662414736: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662414352: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662413968: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661230288: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662412816: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662412624: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661230864: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662412432: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662412240: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661232784: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662410512: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662406672: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898661229328: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662413200: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135898662413392: TensorSpec(shape=(), dtype=tf.resource, name=None)
 Model_C_UltraLight QAT saved. Time: 112.78s

## **Evaluation**

In [ ]:
def evaluate_tflite_and_measure(file_path, X_test, y_test):

    interpreter = tf.lite.Interpreter(model_path=file_path)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]

    correct = 0
    start_eval = time.perf_counter()

    for i in range(len(X_test)):
        # Ensure data is float32
        input_data = X_test[i:i+1].astype(np.float32)
        interpreter.set_tensor(input_details['index'], input_data)
        interpreter.invoke()
        output_data = interpreter.get_tensor(output_details['index'])

        if np.argmax(output_data) == y_test[i]:
            correct += 1

    eval_duration = time.perf_counter() - start_eval

    avg_latency_ms = (eval_duration / len(X_test)) * 1000
    accuracy = correct / len(X_test)
    size_kb = os.path.getsize(file_path) / 1024

    return accuracy, size_kb, avg_latency_ms

final_benchmark = []

if 'ptq_metadata' in globals() and ptq_metadata:
    for entry in ptq_metadata:
        acc, size, lat = evaluate_tflite_and_measure(entry["path"], X_test, y_test)

        final_benchmark.append({
            "Model": entry["Model"],
            "Type": "PTQ",
            "Total Parameters": entry["Total Parameters"],
            "Final Val Acc": f"{acc:.2%}",
            "Est. Memory (KB)": round(size, 2),
            "Train Time (sec)": entry["Train Time (sec)"],
            "Inf Latency (ms)": round(lat, 2)
        })

if 'qat_metadata' in globals() and qat_metadata:
    for entry in qat_metadata:
        acc, size, lat = evaluate_tflite_and_measure(entry["path"], X_test, y_test)

        final_benchmark.append({
            "Model": entry["Model"],
            "Type": "QAT",
            "Total Parameters": entry["Total Parameters"],
            "Final Val Acc": f"{acc:.2%}",
            "Est. Memory (KB)": round(size, 2),
            "Train Time (sec)": entry["Train Time (sec)"],
            "Inf Latency (ms)": round(lat, 2)
        })

results_df = pd.DataFrame(final_benchmark)
final_csv_path = os.path.join(results_path, 'ptq_qat_analysis.csv')
results_df.to_csv(final_csv_path, index=False)

print("\n FINAL COMPRESSION EXPERIMENT ANALYSIS:")
display(results_df)

/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/interpreter.py:457: UserWarning:     Warning: tf.lite.Interpreter is deprecated and is scheduled for deletion in
    TF 2.20. Please use the LiteRT interpreter from the ai_edge_litert package.
    See the [migration guide](https://ai.google.dev/edge/litert/migration)
    for details.

  warnings.warn(_INTERPRETER_DELETION_WARNING)

 FINAL COMPRESSION EXPERIMENT ANALYSIS:

,Model,Type,Total Parameters,Final Val Acc,Est. Memory (KB),Train Time (sec),Inf Latency (ms)
0,Model_A_Standard,PTQ,"215,683",93.28%,219.02,2.74,0.62
1,Model_B_Separable,PTQ,"3,283",92.32%,12.22,1.96,0.37
2,Model_C_UltraLight,PTQ,"1,884",84.31%,9.66,1.68,0.17
3,Model_A_Standard,QAT,"215,898",93.28%,217.93,156.40,0.71
4,Model_B_Separable,QAT,"3,514",92.64%,13.27,144.61,0.48
5,Model_C_UltraLight,QAT,"2,015",82.60%,9.48,112.78,0.16

## Merge Analysis

In [ ]:
baseline_csv = os.path.join(results_path, 'baseline_model_comparison.csv')
final_analysis_csv = os.path.join(results_path, 'ptq_qat_analysis.csv')

if os.path.exists(baseline_csv) and os.path.exists(final_analysis_csv):

    df_base = pd.read_csv(baseline_csv)
    df_opt = pd.read_csv(final_analysis_csv)

    df_base_clean = df_base.rename(columns={
        'Model Architecture': 'Model',
        'Final Val Acc': 'Acc',
        'Est. Memory (KB)': 'Size (KB)',
        'Inf Latency (ms)': 'Latency (ms)'
    })
    df_base_clean['Type'] = 'Baseline'

    df_opt_clean = df_opt.rename(columns={
        'Final Val Acc': 'Acc',
        'Est. Memory (KB)': 'Size (KB)',
        'Inf Latency (ms)': 'Latency (ms)'
    })

    df_final = pd.concat([df_base_clean, df_opt_clean], ignore_index=True)

    def clean_val(x):
        if isinstance(x, str):
            return float(x.replace('%', '').replace(',', ''))
        return x

    df_final['Size (KB)'] = df_final['Size (KB)'].apply(clean_val).round(2)
    df_final['Latency (ms)'] = df_final['Latency (ms)'].apply(clean_val).round(2)
    df_final['Train Time (sec)'] = df_final['Train Time (sec)'].apply(clean_val).round(2)

    def to_percent(x):
        val = clean_val(x)
        if val <= 1.0: val *= 100
        return f"{val:.2f}%"

    df_final['Acc'] = df_final['Acc'].apply(to_percent)

    cols = ['Model', 'Type', 'Total Parameters', 'Acc', 'Size (KB)', 'Train Time (sec)', 'Latency (ms)']
    df_final = df_final[cols]

    final_csv_path = os.path.join(results_path, 'final_result.csv')
    df_final.to_csv(final_csv_path, index=False)

    print(f" Master Result saved to: {final_csv_path}")
    display(df_final)
else:
    print(" Error: Missing baseline_model_comparison.csv or final_analysis.csv")

 Master Result saved to: /content/drive/MyDrive/speech_commands_project/results/final_result.csv

,Model,Type,Total Parameters,Acc,Size (KB),Train Time (sec),Latency (ms)
0,Model_A_Standard,Baseline,"215,683",90.61%,842.51,446.26,1.30
1,Model_B_Separable,Baseline,"3,283",89.75%,12.82,350.05,1.07
2,Model_C_UltraLight,Baseline,"1,884",86.02%,7.36,277.58,1.05
3,Model_A_Standard,PTQ,"215,683",93.28%,219.02,2.74,0.62
4,Model_B_Separable,PTQ,"3,283",92.32%,12.22,1.96,0.37
5,Model_C_UltraLight,PTQ,"1,884",84.31%,9.66,1.68,0.17
6,Model_A_Standard,QAT,"215,898",93.28%,217.93,156.40,0.71
7,Model_B_Separable,QAT,"3,514",92.64%,13.27,144.61,0.48
8,Model_C_UltraLight,QAT,"2,015",82.60%,9.48,112.78,0.16